#!/bin/sh
#
# Standard resolv.conf
#

start() {
	printf "Starting /etc/resolv.conf file: "
	echo "nameserver 8.8.8.8" >> /etc/resolv.conf
	echo "nameserver 8.8.4.4" >> /etc/resolv.conf
	echo "OK"
}

stop() {
	echo "Bye bye"
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	stop
	start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
